# Generated by Django 3.2.23 on 2023-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('is_precessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ContactForm',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='home',
            name='chair_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='chair_price',
        ),
    ]
