# Generated by Django 3.2.23 on 2023-12-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0003_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
    ]
