# Generated by Django 3.2.23 on 2024-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0005_auto_20240102_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
